import { directives } from './directives.ts';

export const enComponents = [
  { text: 'Accordion', link: '/components/accordion/accordion.doc' },
  { text: 'Alert', link: '/components/alert/alert.doc' },
  // { text: 'Autocomplete', link: '/components/autocomplete/autocomplete.doc' },
  { text: 'Breadcrumbs', link: '/components/breadcrumbs/breadcrumbs.doc' },
  { text: 'Button', link: '/components/button/button.doc' },
  { text: 'ButtonGroup', link: '/components/button-group/buttonGroup.doc' },
  { text: 'Card', link: '/components/card/card.doc' },
  // { text: 'Carousel', link: '/components/carousel/carousel.doc' },
  { text: 'Cascader', link: '/components/cascader/cascader.doc' },
  { text: 'Checkbox', link: '/components/checkbox/checkbox.doc' },
  { text: 'Chip', link: '/components/chip/chip.doc' },
  { text: 'Code', link: '/components/code/code.doc' },
  { text: 'Column', link: '/components/column/column.doc' },
  { text: 'ConfigProvider', link: '/components/configProvider/configProvider.doc' },
  { text: 'Combobox', link: '/components/combobox/combobox.doc' },
  { text: 'Container', link: '/components/container/container.doc' },
  { text: 'Data Table', link: '/components/table/table.doc' },
  { text: 'Dialog', link: '/components/dialog/dialog.doc' },
  { text: 'Divider', link: '/components/divider/divider.doc' },
  // { text: 'Drawer', link: '/components/drawer/drawer.doc' },
  { text: 'Dropdown', link: '/components/dropdown/dropdown.doc' },
  { text: 'FittedActions', link: '/components/fitted-actions/fittedActions.doc' },
  { text: 'Footer', link: '/components/footer/footer.doc' },
  { text: 'Grid', link: '/components/grid/grid.doc' },
  { text: 'Header', link: '/components/header/header.doc' },
  { text: 'Icon', link: '/components/icon/icon.doc' },
  { text: 'IconButton', link: '/components/icon-button/iconButton.doc' },
  { text: 'Input', link: '/components/input/input' },
  { text: 'Link', link: '/components/link/link.doc' },
  { text: 'List', link: '/components/list/list.doc' },
  { text: 'Main', link: '/components/main/main.doc' },
  { text: 'Markup Table', link: '/components/markup-table/markupTable.doc' },
  { text: 'Menu', link: '/components/menu/menu.doc' },
  // { text: 'Notification', link: '/components/notification.doc' },
  // { text: 'PieChart', link: '/components/pie-chart/pieChart.doc' },
  { text: 'Popover', link: '/components/popover/popover.doc' },
  { text: 'Popper', link: '/components/popper/popper.doc' },
  // { text: 'Progress', link: '/components/progress/progress.doc' },
  // { text: 'Radio', link: '/components/radio/radio.doc' },
  { text: 'Ribbon', link: '/components/ribbon/ribbon.doc' },
  { text: 'Row', link: '/components/row/row.doc' },
  // { text: 'Skeleton', link: '/components/skeleton/skeleton.doc' },
  { text: 'Stepper', link: '/components/stepper/stepper.doc' },
  // { text: 'Steps', link: '/components/steps/steps.doc' },
  // { text: 'Switch', link: '/components/switch/switch.doc' },
  // { text: 'TextArea', link: '/components/textarea/textarea.doc' },
  { text: 'ThemeProvider', link: '/components/themeProvider/themeProvider.doc' },
  { text: 'Toolbar', link: '/components/toolbar/toolbar.doc' },
  { text: 'Tooltip', link: '/components/tooltip/tooltip.doc' },
  { text: 'Tree', link: '/components/tree/tree.doc' },
  // { text: 'Typography', link: '/components/typography/typography.doc' },
  // { text: 'Upload', link: '/components/upload/upload.doc' },
  { text: 'Virtual Scroll', link: '/components/virtual-scroll/virtualScroll.doc' },
  {
    text: 'Directives',
    items: directives,
  },

  // {
  //   text: 'Basic',
  //   items: [
  //     { text: 'Button', link: '/components/button/button.doc' },
  //     { text: 'Alert', link: '/components/alert/alert.doc' },
  //     { text: 'ButtonGroup', link: '/components/button-group' },
  //     { text: 'Icon', link: '/components/icon/icon.doc' },
  //     { text: 'Link', link: '/components/link/link.doc' },
  //   ],
  // },
  // {
  //   text: 'Form',
  //   items: [
  //     { text: 'Autocomplete', link: '/components/autocomplete' },
  //     { text: 'Input', link: '/components/input' },
  //     { text: 'Checkbox', link: '/components/checkbox' },
  //     { text: 'Radio', link: '/components/radio' },
  //     { text: 'TextArea', link: '/components/text-area' },
  //     { text: 'Switch', link: '/components/switch' },
  //     { text: 'Upload', link: '/components/upload' },
  //   ],
  // },
  // {
  //   text: 'Data',
  //   items: [
  //     { text: 'Chip', link: '/components/chip/chip.doc' },
  //     { text: 'List', link: '/components/list/list.doc' },
  //     { text: 'Progress', link: '/components/progress' },
  //     { text: 'Markup Table', link: '/components/markup-table/markupTable.doc' },
  //     { text: 'Data Table', link: '/components/table/table.doc' },
  //     { text: 'Tree', link: '/components/tree/tree.doc' },
  //     { text: 'Typography', link: '/components/typography' },
  //     { text: 'Virtual Scroll', link: '/components/virtual-scroll/virtualScroll.doc' },
  //   ],
  // },
  // {
  //   text: 'Panel',
  //   items: [
  //     { text: 'Accordion', link: '/components/accordion/accordion.doc' },
  //     { text: 'Card', link: '/components/card/card.doc' },
  //     { text: 'Divider', link: '/components/divider/divider.doc' },
  //     { text: 'Toolbar', link: '/components/toolbar' },
  //     { text: 'Stepper', link: '/components/stepper/stepper' },
  //   ],
  // },
  // {
  //   text: 'Feedback',
  //   items: [
  //     { text: 'Alert', link: '/components/alert/alert.doc' },
  //     { text: 'Notification', link: '/components/notification' },
  //   ],
  // },
  // {
  //   text: 'Overlay',
  //   items: [
  //     { text: 'Tooltip', link: '/components/tooltip' },
  //     { text: 'Dialog', link: '/components/dialog' },
  //     { text: 'Popover', link: '/components/popover' },
  //   ],
  // },
  // {
  //   text: 'Navigation',
  //   items: [
  //     { text: 'Breadcrumbs', link: '/components/breadcrumbs/breadcrumbs.doc' },
  //     { text: 'FittedActions', link: '/components/fitted-actions/fittedActions.doc' },
  //     { text: 'Drawer', link: '/components/drawer' },
  //     { text: 'Menu', link: '/components/menu' },
  //     { text: 'Steps', link: '/components/steps' },
  //   ],
  // },
  // {
  //   text: 'Charts',
  //   items: [
  //     { text: 'PieChart', link: '/components/pie-chart' },
  //   ],
  // },
  // {
  //   text: 'Media',
  //   items: [
  //     { text: 'Carousel', link: '/components/carousel' },
  //   ],
  // },
  // {
  //   text: 'Utils',
  //   items: [
  //     { text: 'Collapse', link: '/components/collapse' },
  //     { text: 'Skeleton', link: '/components/skeleton/skeleton.doc' },
  //   ],
  // },
];
